In [1]:
from sst import SST
sst = SST()

In [2]:
w =  sst.section('W360x196')
sst.show(w)

,0,Expo,Units,Property Description
Prp,*,,,"Property group, '*' indicates the first sectio..."
Dsg,W360x196,,,Section designation
Avl,*,,,"Availability, '*' indicates a section not prod..."
Shp,1,,,Shape identification code. See 'Contents' above.
Grp,,,,G40.20 shape size grouping for tensile propert...
Use,1,,,"Normal use, 1-column, 2-column or beam, 3-beam..."
D,372,,$mm$,"Depth of section or height of vertical leg, mm."
B,374,,$mm$,"Width of flange or horizontal leg, mm."
T,26.2,,$mm$,"Thickness of flange, leg or wall, mm."
W,16.4,,$mm$,"Thickness of web, mm."
BT,7.14,,,"Width-to-thickness ratio of flange, wall or ho..."
HW,19.5,,,Clear depth-to-thickness ratio of web. See S16...
K,58,,$mm$,Distance between outer face of flange and web-...
K1,38,,$mm$,Distance between middle line of web and flange...
Dnom,360,,$mm$,"Nominal depth of section, mm."
Mass,196,,$kg/m$,"Mass per length, kg/m."
A,25000,,$mm^2$,"Cross-sectional area, mm^2."
Ix,636,$\times 10^6$,$mm^4$,"Moment of inertia about axis XX, mm^4."
Sx,3420,$\times 10^3$,$mm^3$,"Elastic section modulus about axis XX, mm^3."
Rx,159,,$mm$,"Radius of gyration about axis XX, mm."
Zx,3840,$\times 10^3$,$mm^3$,"Plastic modulus about axis XX, mm^3."
Iy,229,$\times 10^6$,$mm^4$,"Moment of inertia about axis YY, mm^4."
Sy,1220,$\times 10^3$,$mm^3$,"Elastic section modulus about axis YY, mm^3."
Ry,95.5,,$mm$,"Radius of gyration about axis YY, mm."
Zy,1860,$\times 10^3$,$mm^3$,"Plastic modulus about axis YY, mm^3."
J,5140,$\times 10^3$,$mm^4$,"St-Venant torsional constant, mm^4."
Cw,6830,$\times 10^9$,$mm^6$,"Warping constant, mm^6."
Wn,32300,,$mm^2$,"Normalized unit warping function, mm^2."
Sw,79.2,$\times 10^6$,$mm^4$,"Warping statical moment, mm^4."
Qf,810,$\times 10^3$,$mm^3$,Statical moment at point in flange in line wit...
Qw,1900,$\times 10^3$,$mm^3$,"Statical moment at mid-depth in web, mm^3."
SA,2.21,,$m$,"Surface area per metre, m."
Ds_i,W14x132,,,Section designation (Imperial units).
Dn_i,14,,$in$,"Nominal depth of section (Imperial units), in."
Wt_i,132,,$lb/ft$,"Weight per length (Imperial units), lb/ft."

In [3]:
wl = sst.section_tables(['W','WWF'],'Mass')

def myfunc0(shape,Fy=300.,M=0.):
    My = Fy * shape.Sx / 1E6
    if My >= M:
        return dict(My=My)

s = sst.select_rows(wl,myfunc0,maxn=5,Fy=350.,M=500.)
s[['Mass','Sx','My']]

         Mass         Sx     My
W530x72  72.0  1520000.0  532.0
W460x74  74.0  1460000.0  511.0
W530x74  74.0  1550000.0  542.5
W460x82  82.0  1610000.0  563.5
W610x82  82.0  1880000.0  658.0

In [4]:
def myfunc(Zx,Fy=350.,Mf=0):
    Mp = Fy * Zx / 1E6
    if Mp >= Mf:
        return dict(Mp=Mp,Foo=13,Fy=Fy,Mf=Mf)
    return False

s = sst.select(wl,myfunc,maxn=10,Mf=2000)
s[['Mass','Avl','Use','Zx','Mp','Foo','Fy','Mf']]

             Mass  Avl  Use         Zx      Mp  Foo     Fy    Mf
WWF800x161  161.0  NaN  3.0  6320000.0  2212.0   13  350.0  2000
WWF900x169  169.0  NaN  3.0  7370000.0  2579.5   13  350.0  2000
W760x173    173.0    *  3.0  6210000.0  2173.5   13  350.0  2000
WWF700x175  175.0  NaN  3.0  6260000.0  2191.0   13  350.0  2000
W840x176    176.0    *  3.0  6810000.0  2383.5   13  350.0  2000
WWF800x184  184.0  NaN  3.0  7410000.0  2593.5   13  350.0  2000
W760x185    185.0    *  3.0  6690000.0  2341.5   13  350.0  2000
W690x192    192.0    *  3.0  6460000.0  2261.0   13  350.0  2000
WWF900x192  192.0  NaN  3.0  8600000.0  3010.0   13  350.0  2000
W840x193    193.0    *  3.0  7620000.0  2667.0   13  350.0  2000

In [5]:
s = sst.select(wl,myfunc,Fy=400.,Mf=300.,maxn=20)
s[['Mass','Avl','Use','Zx','Mp','Foo','Fy','Mf']].sort_values('Mp',ascending=False)

         Mass Avl  Use         Zx     Mp  Foo     Fy     Mf
W530x66  66.0  *C  3.0  1560000.0  624.0   13  400.0  300.0
W460x68  68.0  *C  3.0  1490000.0  596.0   13  400.0  300.0
W460x67  67.0   +  3.0  1470000.0  588.0   13  400.0  300.0
W410x67  67.0  *C  3.0  1360000.0  544.0   13  400.0  300.0
W460x61  61.0   +  3.0  1290000.0  516.0   13  400.0  300.0
W460x60  60.0  *C  3.0  1280000.0  512.0   13  400.0  300.0
W410x60  60.0  *C  3.0  1190000.0  476.0   13  400.0  300.0
W360x64  64.0  *C  2.0  1140000.0  456.0   13  400.0  300.0
W460x52  52.0  *C  3.0  1090000.0  436.0   13  400.0  300.0
W410x54  54.0  *C  3.0  1050000.0  420.0   13  400.0  300.0
W310x67  67.0  *C  2.0  1050000.0  420.0   13  400.0  300.0
W360x57  57.0  *C  3.0  1010000.0  404.0   13  400.0  300.0
W310x60  60.0  *C  2.0   933000.0  373.2   13  400.0  300.0
W250x67  67.0  *C  2.0   901000.0  360.4   13  400.0  300.0
W360x51  51.0  *C  3.0   894000.0  357.6   13  400.0  300.0
W410x46  46.0  *C  3.0   885000.0  354.0   13  400.0  300.0
W310x52  52.0  *C  3.0   841000.0  336.4   13  400.0  300.0
W200x71  71.0  *C  2.0   803000.0  321.2   13  400.0  300.0
W360x45  45.0  *C  3.0   779000.0  311.6   13  400.0  300.0
W250x58  58.0  *C  2.0   770000.0  308.0   13  400.0  300.0

In [6]:
slb = sst.section_table('SLB')
slb

,Prp,Dsg,Avl,Shp,Grp,Use,D,B,T,W,...,Zy,J,Cw,T1,T2,Slp,SA,Ds_i,Dn_i,Wt_i
Dsg,,,,,,,,,,,,,,,,,,,,,
SLB100x5.4,*,SLB100x5.4,NaN,18,1.0,3.0,101.6,57.2,3.28,3.18,...,5490.0,2860.0,240000000.0,3.04,3.52,0.02,0.43,SLB4x3.64,4.00,3.64
SLB100x5.1,NaN,SLB100x5.1,NaN,18,1.0,3.0,101.6,57.2,3.45,2.54,...,5680.0,2500.0,250000000.0,3.21,3.69,0.02,0.43,SLB4x3.45,4.00,3.45
SLB100x4.8,NaN,SLB100x4.8,NaN,18,1.0,3.0,101.6,57.2,3.28,2.34,...,5370.0,2120.0,240000000.0,3.04,3.52,0.02,0.43,SLB4x3.20,4.00,3.20
SLB75x5.6,*,SLB75x5.6,NaN,18,1.0,3.0,77.0,57.2,4.32,2.79,...,7080.0,4440.0,170000000.0,4.08,4.56,0.02,0.38,SLB3x3.75,3.00,3.75
SLB75x4.5,NaN,SLB75x4.5,NaN,18,1.0,3.0,76.2,57.2,3.53,2.29,...,5740.0,2280.0,140000000.0,3.29,3.77,0.02,0.38,SLB3x3.05,3.00,3.05
SLB75x4.3,NaN,SLB75x4.3,NaN,18,1.0,3.0,76.2,57.2,3.30,2.21,...,5360.0,1920.0,130000000.0,3.06,3.54,0.02,0.38,SLB3x2.90,3.00,2.90
SLB75x3.8,NaN,SLB75x3.8,NaN,18,1.0,3.0,76.2,50.8,3.07,2.21,...,3960.0,1510.0,90000000.0,2.86,3.28,0.02,0.35,SLB3x2.54,3.00,2.54
SLB55x6.4,*,SLB55x6.4,NaN,18,1.0,3.0,57.2,69.9,4.85,2.54,...,11700.0,6120.0,180000000.0,4.56,5.14,0.02,0.39,SLB2.25x4.30,2.25,4.30

In [8]:
def foo(x):
    print(x)
    return x == 'SLB75x5.6'
slb.select(foo)

AttributeError: 'DataFrame' object has no attribute 'select'

In [9]:
s = 'SLB75x5.6'
slb.ix[s]

AttributeError: 'DataFrame' object has no attribute 'ix'

In [10]:
slb[['B']].index

Index(['SLB100x5.4', 'SLB100x5.1', 'SLB100x4.8', 'SLB75x5.6', 'SLB75x4.5',
       'SLB75x4.3', 'SLB75x3.8', 'SLB55x6.4'],
      dtype='object', name='Dsg')

In [12]:
for i in range(1,22):
    t = sst.section_table(i)
    print(i, len(t))

1 281
2 28
3 12
4 11
5 107
6 32
7 34
8 139
9 188
10 41
11 73
12 73
13 66
14 15
15 62
16 62
17 67
18 8
19 62
20 62
21 67